# frozen_string_literal: true

require 'pg'

def setup_database
  create_database
  create_table
  puts 'データベースの設定が成功しました'
end

def create_database
  default_conn = PG.connect(dbname: 'postgres')
  default_conn.exec('CREATE DATABASE memo;') do
  end
end

def create_table
  conn = PG.connect(dbname: 'memo')
  conn.exec(<<~SQL) do
    CREATE TABLE IF NOT EXISTS memos (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title VARCHAR NOT NULL,
      content TEXT NOT NULL
    );
  SQL
  end
end

setup_database
