# frozen_string_literal: true

require 'pg'
require_relative 'config/db_config'

def setup_database
  create_database
  create_table
end

def create_database
  begin
    default_conn = PG.connect( dbname: DEFAULT_DATABASE)
    default_conn.exec("CREATE DATABASE #{DATABASE_NAME};")
  rescue PG::Error => e
    puts "error： #{e.class} #{e.message}"
    puts "db_config.rbのDATABASE_NAMEの値(#{DATABASE_NAME})を変更して実行してください"
    default_conn.finish
    puts "データベースとの接続を遮断して終了します"
    exit
  end
  default_conn.finish
end

def create_table
  conn = PG.connect( dbname: DATABASE_NAME)
  conn.exec(<<~SQL)
    CREATE TABLE IF NOT EXISTS #{TABLE_NAME} (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title VARCHAR NOT NULL,
      content TEXT NOT NULL
    );
  SQL
  conn.finish
end

setup_database
